keys:
  - &chronos age1xady55247k9tvmcgrlsx6jgtvh2h566thyyxhfp5f054cf6q89psk4t282
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
    - age:
      - *chronos

  - path_regex: secrets/hosts/[^/]+\.yaml$
    key_groups:
      - age: 
        - *chronos