# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../third-party/staypls.nix
  ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ "cryptd" ];
  boot.initrd.systemd.tpm2.enable = true;
  security.tpm2.enable = true;
  boot.kernelModules = ["kvm-intel"];
  boot.extraModulePackages = [];

  services.fprintd.enable = true;

  staypls = {
    enable = true;
    dirs = [
      "/etc/nixos"
      "/etc/ssh"
      "/etc/NetworkManager"
      "/var/log"
      "/var/lib"
      "/usr/systemd-placeholder"
    ];
  };

  boot.initrd.luks.devices = {
    nix = {
      device = "/dev/disk/by-label/NIXROOT";
    };
    home = {
      device = "/dev/disk/by-label/NIXHOME";
    };
    workspace = {
      device = "/dev/disk/by-label/WORKSPACE";
    };
    cryolite = {
      device = "/dev/disk/by-label/CRYOLITE";
    };
    swap = {
      device = "/dev/disk/by-label/SWAP";
    };
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["size=512M" "mode=755"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@nix" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/persist" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@persist" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/tmp" = {
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@tmp" "x-gvfs-hide"];
  };

  fileSystems."/home" = {
    neededForBoot = true;
    device = "/dev/mapper/home";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@home" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/etc/cryolite" = {
    device = "/dev/mapper/cryolite";
    fsType = "ext4";
    options = ["noatime" "x-gvfs-hide"];
  };

  fileSystems."/usr" = {
    device = "/persist/usr";
    fsType = "none";
    options = ["bind" "X-fstrim.notrim" "x-gvfs-hide"];
  };

  fileSystems."/mnt/workspace" = {
    device = "/dev/mapper/workspace";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@workspace" "compress=zstd" "x-gvfs-hide"];
  };

  swapDevices = [
    {
      device = "/dev/mapper/swap";
    }
  ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
