# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  pkgs,
  config,
  lib,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../third-party/staypls.nix
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = ["cryptd" "i915"];
  boot.initrd.systemd.tpm2.enable = true;
  security.tpm2.enable = true;
  boot.kernelModules = ["kvm-intel" "acpi_call"];
  boot.extraModulePackages = [config.boot.kernelPackages.acpi_call];
  boot.kernelParams = [
    "acpi_backlight=native"
  ];

  services.thermald.enable = true;
  services.fprintd.enable = true;

  hardware.graphics = {
    enable = true;
    extraPackages = builtins.attrValues {
      inherit
        (pkgs)
        intel-media-driver
        intel-vaapi-driver
        vpl-gpu-rt
        libvdpau-va-gl
        intel-compute-runtime
        ;
    };
  };

  services.tlp = {
    enable = true;
    pd.enable = true;
    settings = {
      CPU_SCALING_GOVERNOR_ON_AC = "performance";
      CPU_SCALING_GOVERNOR_ON_BAT = "powersave";

      CPU_ENERGY_PERF_POLICY_ON_BAT = "power";
      CPU_ENERGY_PERF_POLICY_ON_AC = "performance";

      CPU_MIN_PERF_ON_AC = 0;
      CPU_MAX_PERF_ON_AC = 100;
      CPU_MIN_PERF_ON_BAT = 0;
      CPU_MAX_PERF_ON_BAT = 40;

      START_CHARGE_THRESH_BAT0 = 40;
      STOP_CHARGE_THRESH_BAT0 = 80;
    };
  };

  services.power-profiles-daemon.enable = lib.mkForce false;

  services.xserver.videoDrivers = lib.mkForce ["i915" "intel"];
  environment.sessionVariables = {LIBVA_DRIVER_NAME = "iHD";};

  staypls = {
    enable = true;
    dirs = [
      "/etc/nixos"
      "/etc/ssh"
      "/etc/NetworkManager"
      "/var/log"
      "/var/lib"
      "/usr/systemd-placeholder"
    ];
  };

  boot.initrd.luks.devices = {
    nix = {
      device = "/dev/disk/by-label/NIXROOT";
    };
    home = {
      device = "/dev/disk/by-label/NIXHOME";
    };
    workspace = {
      device = "/dev/disk/by-label/WORKSPACE";
    };
    cryolite = {
      device = "/dev/disk/by-label/CRYOLITE";
    };
    swap = {
      device = "/dev/disk/by-label/SWAP";
    };
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["size=512M" "mode=755"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/nix" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@nix" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/persist" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@persist" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/var/tmp" = {
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@tmp" "x-gvfs-hide"];
  };

  fileSystems."/home" = {
    neededForBoot = true;
    device = "/dev/mapper/home";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@home" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/etc/cryolite" = {
    device = "/dev/mapper/cryolite";
    fsType = "ext4";
    options = ["noatime" "x-gvfs-hide"];
  };

  fileSystems."/usr" = {
    device = "/persist/usr";
    fsType = "none";
    options = ["bind" "X-fstrim.notrim" "x-gvfs-hide"];
  };

  fileSystems."/mnt/workspace" = {
    device = "/dev/mapper/workspace";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@workspace" "compress=zstd" "x-gvfs-hide"];
  };

  swapDevices = [
    {
      device = "/dev/mapper/swap";
    }
  ];

  boot.tmp.useTmpfs = true;

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
