# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
# I don't care Nix, I edited it manually anyway :3
{
  config,
  lib,
  modulesPath,
  pkgs,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
    ../../third-party/staypls.nix
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.blacklistedKernelModules = ["k10temp"];
  # boot.initrd.kernelModules = ["amdgpu"]; # This broke everything
  boot.initrd.systemd.tpm2.enable = true;
  security.tpm2.enable = true;
  boot.kernelModules = ["kvm-amd" "zenpower"];
  boot.extraModulePackages = [config.boot.kernelPackages.zenpower];
  boot.kernelParams = [
    "amdgpu.ppfeaturemask=0xfffd3fff"
    "amdgpu.lockup_timeout=10000"
    "amdgpu.gpu_recovery=1"
    "amdgpu.dc=1"
  ];

  # hardware.amdgpu.initrd.enable = lib.mkDefault true;
  hardware.graphics = {
    enable = lib.mkDefault true;
    enable32Bit = lib.mkDefault true;
    extraPackages = [pkgs.rocmPackages.clr.icd];
  };

  environment.variables = {
    ROC_ENABLE_PRE_VEGA = "1";
  };

  services.xserver.videoDrivers = lib.mkDefault ["amdgpu"];

  staypls = {
    enable = true;
    dirs = [
      "/etc/nixos"
      "/etc/ssh"
      "/etc/NetworkManager"
      "/var/log"
      "/var/lib"
      "/usr/systemd-placeholder"
    ];
  };

  boot.initrd.luks.devices = {
    nix = {
      device = "/dev/disk/by-label/NIXROOT";
    };
    home = {
      device = "/dev/disk/by-label/NIXHOME";
    };
    cryolite = {
      device = "/dev/disk/by-label/CRYOLITE";
    };
    swap = {
      device = "/dev/disk/by-label/SWAP";
    };
  };

  fileSystems."/" = {
    device = "none";
    fsType = "tmpfs";
    options = ["size=512M" "mode=755"];
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/EFI";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077" "umask=0077"];
  };

  fileSystems."/nix" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@nix" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/persist" = {
    neededForBoot = true;
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@persist" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/tmp" = {
    device = "/dev/mapper/nix";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@tmp" "x-gvfs-hide"];
  };

  fileSystems."/home" = {
    neededForBoot = true;
    device = "/dev/mapper/home";
    fsType = "btrfs";
    options = ["noatime" "discard" "subvol=@home" "compress=zstd" "x-gvfs-hide"];
  };

  fileSystems."/etc/cryolite" = {
    device = "/dev/mapper/cryolite";
    fsType = "ext4";
    options = ["noatime" "x-gvfs-hide"];
  };

  fileSystems."/usr" = {
    device = "/persist/usr";
    fsType = "none";
    options = ["bind" "X-fstrim.notrim" "x-gvfs-hide"];
  };

  # Lemme mount the disks!!
  fileSystems."/mnt/nvme2" = {
    device = "/dev/disk/by-uuid/312796d5-6334-4957-a40f-50311f2b7749";
    fsType = "ext4";
    options = ["defaults" "noatime" "nodiratime" "discard" "nosuid"];
  };

  fileSystems."/mnt/workspace" = {
    device = "/dev/disk/by-uuid/f6302143-2559-4e77-abc7-0a57d942d2dc";
    fsType = "btrfs";
  };

  swapDevices = [
    {device = "/dev/mapper/swap";}
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp5s0.useDHCP = lib.mkDefault true;

  powerManagement.cpuFreqGovernor = "performance";
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
